// <auto-generated />
namespace MJIoT_DBModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FixedTypoInConnections_ContitionValueToConditionValue : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixedTypoInConnections_ContitionValueToConditionValue));
        
        string IMigrationMetadata.Id
        {
            get { return "201803311426059_FixedTypoInConnections_ContitionValueToConditionValue"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
